### ISSUE TITLE
Request : setting initial position of debug tool

### ISSUE THREAD

**Issue by chesteryu** [hulab/debugkit#4]
First of all thanks for the library. It really helps a lot, but I have some suggestions.

It may be helpful to allow setting the initial position of the debug tool. I am using this library on TV apps, using a remote control to drag around the debug tool is quite some hassle. It will be great if I can place it to some unimportant corner initially.

**Comment by Nebneb** [comment]
Hi Chesteryu! Thank you for your support, I'm glad to see this debugkit is useful for Android TV development as well. It seems legit and as it's easy on my side, I'll try to do it and release it today. I'll let you know.

**Comment by Nebneb** [comment]
Done and released now (v1.2.0). You can call `displayAt(X,Y)`on your builder to specify the initial position of the view (in pixels).
Closing the issue, but don't hesitate to re-open it if it doesn't fit your expectation.
