### ISSUE TITLE
Request : Allow clearing logs on the console

### ISSUE THREAD

**Issue by chesteryu** [hulab/debugkit#5]
There are apparent performance drops after logging quite a number of lines. And I think people will not often looking for logs 3000 lines earlier anyway.

Adding a public function to clear logs may help.

**Comment by Nebneb** [comment]
Hi again,
Same as previous, I'll add it in the next release.

**Comment by Nebneb** [comment]
Done and released now (v1.2.0), just call `clear()` in your debug function call implementation or directly add the prebuilt `DebugFunction.Clear` function.
I'm closing the issue, but don't hesitate to re-open it if it doesn't fit your expectations.
